language: node_js
node_js:
  - 6.10
sudo: required

services:
  - docker

before_install:
  - docker pull postgres
  - docker run --privileged -d -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres  -e POSTGRES_DB=ts-api --name postgres -p 5432 --restart=always postgres
  - docker ps -a

# script:
#   - npm test
#   - istanbul cover node_modules/.bin/$}{}
#   - codecov
branches:
  only:
    - master
    - dev
