language: node_js
node_js:
  - 6.10
sudo: required

services:
  - postgresql

before_install:
  - psql -c 'create database travis_ci_test;' -U postgres

# script:
#   - npm test
#   - istanbul cover node_modules/.bin/${test-framework}
#   - codecov
branches:
  only:
    - master
    - dev
